const express = require('express');
const db = require('../db');
const { uid } = require('../db');
const { authenticate, requireCoach } = require('../middleware/auth');

const router = express.Router();
router.use(authenticate, requireCoach);

// Coach dashboard: assigned sessions + roster + student roll-up
router.get('/dashboard', (req, res) => {
  const coachId = req.query.coach_user_id && req.user.role !== 'COACH' ? req.query.coach_user_id : req.user.id;

  const sessions = db.prepare(`
    SELECT s.*, p.name AS planet_name, l.name AS level_name, loc.name AS location_name,
           v.class_setting, b.day_of_week,
           (SELECT COUNT(*) FROM attendance a WHERE a.session_id = s.id) AS expected_count,
           (SELECT COUNT(*) FROM attendance a WHERE a.session_id = s.id AND a.status = 'PRESENT') AS present_count
    FROM sessions s
    JOIN batches b ON b.id = s.batch_id
    JOIN offerings o ON o.id = b.offering_id
    JOIN course_variants v ON v.id = o.variant_id
    JOIN courses c ON c.id = v.course_id
    JOIN levels l ON l.id = c.level_id
    JOIN planets p ON p.id = l.planet_id
    JOIN locations loc ON loc.id = o.location_id
    WHERE s.coach_user_id = ? AND s.session_date >= date('now','-7 days')
    ORDER BY s.session_date, s.start_time`).all(coachId);

  // Assigned students with last topic covered / homework status
  const students = db.prepare(`
    SELECT DISTINCT m.id, m.first_name || ' ' || m.last_name AS name,
           p.name AS planet_name, l.name AS level_name,
           (SELECT sn.topics_covered FROM session_notes sn WHERE sn.member_id = m.id ORDER BY sn.created_at DESC LIMIT 1) AS last_topic,
           (SELECT sn.homework_done FROM session_notes sn WHERE sn.member_id = m.id ORDER BY sn.created_at DESC LIMIT 1) AS last_homework_done
    FROM enrollments e
    JOIN members m ON m.id = e.member_id
    JOIN enrollment_slots es ON es.enrollment_id = e.id
    JOIN batches b ON b.id = es.batch_id
    JOIN sessions s ON s.batch_id = b.id AND s.coach_user_id = ?
    JOIN offerings o ON o.id = e.offering_id
    JOIN course_variants v ON v.id = o.variant_id
    JOIN courses c ON c.id = v.course_id
    JOIN levels l ON l.id = c.level_id
    JOIN planets p ON p.id = l.planet_id
    WHERE e.status IN ('ACTIVE','NOTICE_GIVEN')`).all(coachId);

  const pendingTrials = db.prepare(`
    SELECT t.*, b.day_of_week, b.start_time,
           p.name AS planet_name, l.name AS level_name,
           m.first_name || ' ' || m.last_name AS member_name
    FROM trials t
    JOIN batches b ON b.id = t.batch_id
    JOIN offerings o ON o.id = b.offering_id
    JOIN course_variants v ON v.id = o.variant_id
    JOIN courses c ON c.id = v.course_id
    JOIN levels l ON l.id = c.level_id
    JOIN planets p ON p.id = l.planet_id
    LEFT JOIN members m ON m.id = t.member_id
    WHERE t.id NOT IN (SELECT trial_id FROM trial_assessments)
      AND t.ownership_id = (SELECT ownership_id FROM users WHERE id = ?)
    ORDER BY t.trial_date`).all(coachId);

  const availability = db.prepare('SELECT * FROM coach_availability WHERE coach_user_id = ? ORDER BY day_of_week').all(coachId);
  const leaves = db.prepare('SELECT * FROM coach_leaves WHERE coach_user_id = ? ORDER BY from_date').all(coachId);

  res.json({ sessions, students, pending_trials: pendingTrials, availability, leaves });
});

// Attendance sheet for one session (expected roll generated by the System actor)
router.get('/sessions/:id/attendance', (req, res) => {
  const s = db.prepare('SELECT * FROM sessions WHERE id = ?').get(req.params.id);
  if (!s) return res.status(404).json({ error: 'Session not found' });
  const rows = db.prepare(`
    SELECT a.*, m.first_name || ' ' || m.last_name AS member_name
    FROM attendance a JOIN members m ON m.id = a.member_id
    WHERE a.session_id = ? ORDER BY member_name`).all(s.id);
  const notes = db.prepare('SELECT * FROM session_notes WHERE session_id = ?').all(s.id);
  res.json({ session: s, attendance: rows, notes });
});

// Mark attendance
router.put('/attendance/:id', (req, res) => {
  const { status } = req.body;
  if (!['PRESENT', 'ABSENT', 'LATE', 'MAKEUP', 'TRIAL'].includes(status)) {
    return res.status(400).json({ error: 'Invalid attendance status' });
  }
  const a = db.prepare('SELECT * FROM attendance WHERE id = ?').get(req.params.id);
  if (!a) return res.status(404).json({ error: 'Attendance row not found' });
  db.prepare(`UPDATE attendance SET status = ?, marked_by = ?, marked_at = datetime('now') WHERE id = ?`)
    .run(status, req.user.id, a.id);

  // Missed-class notification to the parent
  if (status === 'ABSENT') {
    const parent = db.prepare(`
      SELECT u.id AS user_id, m.first_name FROM members m
      JOIN customers c ON c.id = m.customer_id JOIN users u ON u.id = c.user_id WHERE m.id = ?`).get(a.member_id);
    if (parent) {
      db.prepare(`INSERT INTO notifications (id,user_id,type,message) VALUES (?,?,?,?)`)
        .run(uid(), parent.user_id, 'MISSED_CLASS', `${parent.first_name} missed a class today.`);
    }
  }
  res.json({ success: true });
});

// Session notes: topics covered, homework assigned/done (per member or whole class)
router.post('/sessions/:id/notes', (req, res) => {
  const s = db.prepare('SELECT * FROM sessions WHERE id = ?').get(req.params.id);
  if (!s) return res.status(404).json({ error: 'Session not found' });
  const { member_id = null, topics_covered, homework_assigned, homework_done } = req.body;
  const id = uid();
  db.prepare(`INSERT INTO session_notes (id,ownership_id,session_id,member_id,topics_covered,homework_assigned,homework_done,coach_user_id)
              VALUES (?,?,?,?,?,?,?,?)`)
    .run(id, s.ownership_id, s.id, member_id, topics_covered || null, homework_assigned || null,
         homework_done == null ? null : (homework_done ? 1 : 0), req.user.id);
  res.status(201).json({ id });
});

// Trial assessment: feedback + attachment + recommended batch. Visible to
// admin/manager and on the parent dashboard for one-click signup.
router.post('/trials/:id/assessment', (req, res) => {
  const t = db.prepare('SELECT * FROM trials WHERE id = ?').get(req.params.id);
  if (!t) return res.status(404).json({ error: 'Trial not found' });
  const { feedback, attachment_url, recommended_batch_id } = req.body;
  if (!feedback) return res.status(400).json({ error: 'Feedback text is required' });
  const id = uid();
  db.prepare(`INSERT INTO trial_assessments (id,ownership_id,trial_id,coach_user_id,feedback,attachment_url,recommended_batch_id)
              VALUES (?,?,?,?,?,?,?)`)
    .run(id, t.ownership_id, t.id, req.user.id, feedback, attachment_url || null, recommended_batch_id || null);
  db.prepare(`UPDATE trials SET status = 'ATTENDED' WHERE id = ? AND status = 'BOOKED'`).run(t.id);
  res.status(201).json({ id });
});

// Availability for the next 6 months, by day of week; carries over unless a
// leave is applied.
router.post('/availability', (req, res) => {
  const { day_of_week, start_time, end_time, effective_from, effective_to } = req.body;
  if (day_of_week == null || !start_time || !end_time) return res.status(400).json({ error: 'day_of_week, start_time and end_time are required' });
  const from = effective_from || new Date().toISOString().slice(0, 10);
  const maxTo = new Date(Date.now() + 183 * 86400000).toISOString().slice(0, 10);
  if (effective_to && effective_to > maxTo) return res.status(400).json({ error: 'Availability can be declared at most 6 months out' });
  const id = uid();
  db.prepare(`INSERT INTO coach_availability (id,ownership_id,coach_user_id,day_of_week,start_time,end_time,effective_from,effective_to)
              VALUES (?,?,?,?,?,?,?,?)`)
    .run(id, req.user.ownership_id, req.user.id, day_of_week, start_time, end_time, from, effective_to || null);
  res.status(201).json({ id });
});

router.delete('/availability/:id', (req, res) => {
  db.prepare('DELETE FROM coach_availability WHERE id = ? AND coach_user_id = ?').run(req.params.id, req.user.id);
  res.json({ success: true });
});

router.post('/leaves', (req, res) => {
  const { from_date, to_date, note } = req.body;
  if (!from_date || !to_date) return res.status(400).json({ error: 'from_date and to_date are required' });
  const id = uid();
  db.prepare(`INSERT INTO coach_leaves (id,ownership_id,coach_user_id,from_date,to_date,note) VALUES (?,?,?,?,?,?)`)
    .run(id, req.user.ownership_id, req.user.id, from_date, to_date, note || null);
  res.status(201).json({ id });
});

router.delete('/leaves/:id', (req, res) => {
  db.prepare('DELETE FROM coach_leaves WHERE id = ? AND coach_user_id = ?').run(req.params.id, req.user.id);
  res.json({ success: true });
});

module.exports = router;
